language: python
python:
  - "2.7"
instal:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
services:
  - docker
deploy:
  provider: heroku
  app: peaceful-headland-56891
  api_key: ${HEROKU_API_KEY}
